;;; document-sections-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from document-sections.el

(autoload 'document-sections-find-section "document-sections" "\
Prompt to visit the projects that related-file knows about." t)
(register-definition-prefixes "document-sections" '("document-sections-"))


;;; End of scraped data

(provide 'document-sections-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; document-sections-autoloads.el ends here
